# Generated by Django 5.0.3 on 2024-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('short_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.IntegerField()),
                ('dates', models.DateField()),
                ('full_description', models.TextField()),
            ],
        ),
    ]
