# Generated by Django 5.0.3 on 2024-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tourpackage_full_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='short_description',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='full_description',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
