# Generated by Django 5.0.3 on 2024-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_tourpackage_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='tourpackage',
            old_name='destination',
            new_name='short_description1',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image2',
            field=models.ImageField(default=100, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image3',
            field=models.ImageField(default=100, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='short_description2',
            field=models.CharField(default=100, max_length=100),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='short_description3',
            field=models.CharField(default=100, max_length=100),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='full_description',
            field=models.CharField(default=100, max_length=200),
        ),
    ]
