# Generated by Django 5.0.3 on 2024-03-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_image_tourpackage_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='short_description1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='short_description2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='short_description3',
            field=models.TextField(),
        ),
    ]
