# Generated by Django 5.0.3 on 2024-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tourpackage_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='image1',
            field=models.ImageField(upload_to='kash/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image2',
            field=models.ImageField(default=100, upload_to='kash/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image3',
            field=models.ImageField(default=100, upload_to='kash/'),
        ),
    ]
