# Generated by Django 5.0.3 on 2024-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_tourpackage_image1_alter_tourpackage_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='location',
            field=models.CharField(default=50, max_length=50),
        ),
    ]
