# Generated by Django 5.0.3 on 2024-04-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tourpackage_name_alter_tourpackage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='short_description3',
        ),
    ]
