# Generated by Django 5.0.3 on 2024-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_tourpackage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
