# Generated by Django 5.0.3 on 2024-04-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_tourpackage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='id',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='package_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
