# Generated by Django 5.0.3 on 2024-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_package_delete_tourpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='imag1',
            new_name='image1',
        ),
    ]
