# Generated by Django 5.0.3 on 2024-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_imag1_package_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/media/kash')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dates', models.DateField()),
                ('shortdescription', models.TextField()),
                ('fulldescription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
