# Generated by Django 5.0.3 on 2024-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_tourpackage_delete_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(upload_to='kash'),
        ),
    ]
