# Generated by Django 5.0.3 on 2024-04-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_tourpackage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourPackage',
            new_name='Package',
        ),
    ]
