# Generated by Django 5.0.3 on 2024-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='ConfirmPassword',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
