# Generated by Django 5.0.3 on 2024-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_userregister_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendorname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(default=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userregister',
            name='ConfirmPassword',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
