# Generated by Django 5.0.3 on 2024-04-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_pakagedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakagedata',
            old_name='ImageName',
            new_name='PackageName',
        ),
    ]
