# Generated by Django 5.0.3 on 2024-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_imagename_pakagedata_packagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakagedata',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
