# Generated by Django 5.0.3 on 2024-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_pakagedata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakagedata',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
