# Generated by Django 5.0.3 on 2024-04-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_pakagedata_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PakageData',
            new_name='PakageDatas',
        ),
    ]
