# Generated by Django 5.0.3 on 2024-04-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_pakagedatas_pakage_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakage_data',
            name='Price',
        ),
    ]
