# Generated by Django 5.0.3 on 2024-04-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_pakage_data_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pakage_Data',
        ),
    ]
