# Generated by Django 5.0.3 on 2024-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_delete_pakage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
