# Generated by Django 5.0.3 on 2024-04-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_package_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Pakage',
        ),
    ]
