# Generated by Django 5.0.3 on 2024-04-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_travelbook_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakage',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='pakage',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
