# Generated by Django 5.0.3 on 2024-04-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_pakage_approved_alter_pakage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PakageAdmin',
            fields=[
                ('pakage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.pakage')),
            ],
            bases=('myapp.pakage',),
        ),
    ]
