# Generated by Django 5.0.3 on 2024-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_pakageadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakage',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
