# Generated by Django 5.0.3 on 2024-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_travelbook_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbook',
            name='firstname',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='travelbook',
            name='lastname',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
