# Generated by Django 5.0.3 on 2024-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_travelbook_firstname_alter_travelbook_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbook',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='travelbook',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
