# Generated by Django 5.0.3 on 2024-04-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_tour_pakage_remove_pakageadmin_pakage_ptr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_Pakage',
            new_name='Pakage',
        ),
    ]
