# Generated by Django 5.0.2 on 2024-04-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_rename_tour_pakage_pakage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakage',
            old_name='end_date',
            new_name='Dates',
        ),
        migrations.RemoveField(
            model_name='pakage',
            name='start_date',
        ),
    ]
