# Generated by Django 5.0.2 on 2024-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_rename_end_date_pakage_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
