# Generated by Django 5.0.2 on 2024-04-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_alter_imagedata_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
